# Generated by Django 4.2.28 on 2026-03-17 22:27

import core.datetimes.ad_datetime
import core.fields
import core.utils
import datetime
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDCISubscription',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('date_valid_from', models.DateTimeField(db_column='DateValidFrom', default=datetime.datetime.now)),
                ('date_valid_to', models.DateTimeField(blank=True, db_column='DateValidTo', null=True)),
                ('replacement_uuid', models.UUIDField(blank=True, db_column='ReplacementUUID', null=True)),
                ('subscription_code', models.CharField(db_column='SubscriptionCode', db_index=True, help_text='Unique subscription identifier returned to client', max_length=255)),
                ('sender_id', models.CharField(db_column='SenderId', help_text='ID of the subscribing system (from header.sender_id)', max_length=255)),
                ('sender_uri', models.URLField(db_column='SenderUri', help_text='Callback URL for notifications (from header.sender_uri)', max_length=500)),
                ('event_type', models.CharField(choices=[('REGISTER', 'Register'), ('UPDATE', 'Update'), ('DEREGISTER', 'Deregister'), ('ALL', 'All events')], db_column='EventType', default='ALL', max_length=50)),
                ('filter_criteria', models.JSONField(blank=True, db_column='FilterCriteria', help_text='SPDCI query filter (idtype-value, expression, predicate)', null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'inactive'), (1, 'active'), (2, 'suspended')], db_column='Status', default=1)),
                ('callback_headers', django_cryptography.fields.encrypt(models.TextField(blank=True, db_column='CallbackHeaders', help_text='Additional HTTP headers for callback (JSON format, encrypted)', null=True))),
                ('expiring', models.DateTimeField(blank=True, db_column='Expiring', help_text='Subscription expiration date (optional)', null=True)),
                ('transaction_id', models.CharField(blank=True, db_column='TransactionId', help_text='Original transaction ID from subscribe request', max_length=255, null=True)),
                ('reference_id', models.CharField(blank=True, db_column='ReferenceId', help_text='Original reference ID from subscribe request', max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_created', models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical DCI Subscription',
                'verbose_name_plural': 'historical DCI Subscriptions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DCISubscription',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('date_valid_from', models.DateTimeField(db_column='DateValidFrom', default=datetime.datetime.now)),
                ('date_valid_to', models.DateTimeField(blank=True, db_column='DateValidTo', null=True)),
                ('replacement_uuid', models.UUIDField(blank=True, db_column='ReplacementUUID', null=True)),
                ('subscription_code', models.CharField(db_column='SubscriptionCode', help_text='Unique subscription identifier returned to client', max_length=255, unique=True)),
                ('sender_id', models.CharField(db_column='SenderId', help_text='ID of the subscribing system (from header.sender_id)', max_length=255)),
                ('sender_uri', models.URLField(db_column='SenderUri', help_text='Callback URL for notifications (from header.sender_uri)', max_length=500)),
                ('event_type', models.CharField(choices=[('REGISTER', 'Register'), ('UPDATE', 'Update'), ('DEREGISTER', 'Deregister'), ('ALL', 'All events')], db_column='EventType', default='ALL', max_length=50)),
                ('filter_criteria', models.JSONField(blank=True, db_column='FilterCriteria', help_text='SPDCI query filter (idtype-value, expression, predicate)', null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'inactive'), (1, 'active'), (2, 'suspended')], db_column='Status', default=1)),
                ('callback_headers', django_cryptography.fields.encrypt(models.TextField(blank=True, db_column='CallbackHeaders', help_text='Additional HTTP headers for callback (JSON format, encrypted)', null=True))),
                ('expiring', models.DateTimeField(blank=True, db_column='Expiring', help_text='Subscription expiration date (optional)', null=True)),
                ('transaction_id', models.CharField(blank=True, db_column='TransactionId', help_text='Original transaction ID from subscribe request', max_length=255, null=True)),
                ('reference_id', models.CharField(blank=True, db_column='ReferenceId', help_text='Original reference ID from subscribe request', max_length=255, null=True)),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DCI Subscription',
                'verbose_name_plural': 'DCI Subscriptions',
                'db_table': 'tblDCISubscription',
                'managed': True,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DCINotificationLog',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_column='EventType', max_length=50)),
                ('resource_type', models.CharField(db_column='ResourceType', help_text='Type of resource (Person, Farmer, Member)', max_length=100)),
                ('resource_id', models.CharField(db_column='ResourceId', help_text='ID of the affected resource', max_length=255)),
                ('notified_successfully', models.BooleanField(db_column='NotifiedSuccessfully')),
                ('notification_time', core.fields.DateTimeField(db_column='NotificationTime', default=core.datetimes.ad_datetime.AdDatetime.now)),
                ('http_status_code', models.IntegerField(blank=True, db_column='HttpStatusCode', null=True)),
                ('error', models.TextField(blank=True, db_column='Error', null=True)),
                ('correlation_id', models.CharField(blank=True, db_column='CorrelationId', help_text='Correlation ID for tracking notifications', max_length=255, null=True)),
                ('subscription', models.ForeignKey(db_column='SubscriptionId', on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to='api_dci.dcisubscription')),
            ],
            options={
                'verbose_name': 'DCI Notification Log',
                'verbose_name_plural': 'DCI Notification Logs',
                'db_table': 'tblDCINotificationLog',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='dcisubscription',
            index=models.Index(fields=['subscription_code'], name='tblDCISubsc_Subscri_9c711f_idx'),
        ),
        migrations.AddIndex(
            model_name='dcisubscription',
            index=models.Index(fields=['sender_id'], name='tblDCISubsc_SenderI_48953e_idx'),
        ),
        migrations.AddIndex(
            model_name='dcisubscription',
            index=models.Index(fields=['status'], name='tblDCISubsc_Status_b6b12c_idx'),
        ),
        migrations.AddIndex(
            model_name='dcisubscription',
            index=models.Index(fields=['event_type'], name='tblDCISubsc_EventTy_91eab3_idx'),
        ),
        migrations.AddIndex(
            model_name='dcinotificationlog',
            index=models.Index(fields=['subscription'], name='tblDCINotif_Subscri_18cbf6_idx'),
        ),
        migrations.AddIndex(
            model_name='dcinotificationlog',
            index=models.Index(fields=['notification_time'], name='tblDCINotif_Notific_ad78ac_idx'),
        ),
        migrations.AddIndex(
            model_name='dcinotificationlog',
            index=models.Index(fields=['notified_successfully'], name='tblDCINotif_Notifie_992688_idx'),
        ),
        migrations.AddIndex(
            model_name='dcinotificationlog',
            index=models.Index(fields=['correlation_id'], name='tblDCINotif_Correla_f38f50_idx'),
        ),
    ]
