# Generated by Django 4.2.28 on 2026-03-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_dci', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcisubscription',
            name='sender_uri',
            field=models.URLField(blank=True, db_column='SenderUri', help_text='Callback URL for notifications (from header.sender_uri, optional)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldcisubscription',
            name='sender_uri',
            field=models.URLField(blank=True, db_column='SenderUri', help_text='Callback URL for notifications (from header.sender_uri, optional)', max_length=500, null=True),
        ),
    ]
